airline/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('flight.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

flight/urls.py
from django.conf.urls import url
from . import views

app_name = 'flight'

urlpatterns = [
    #-------Flights-------
    #/
    url(r'^$', views.IndexView.as_view(), name='index'),

    #/flight/<flight_id>/
    url(r'^flight/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    #/flight/add
    url(r'^flight/add/$', views.FlightCreate.as_view(), name='flight-add'),

    #/flight/<flight_id>/update/
    url(r'^flight/(?P<pk>[0-9]+)/update/$', views.FlightUpdate.as_view(), name='flight-update'),

    #/flight/<flight_id>/delete/
    url(r'^flight/(?P<pk>[0-9]+)/delete/$', views.FlightDelete.as_view(), name='flight-delete'),

    #/search/
    url(r'^search/$', views.search_flights, name='flight-search'),

    #-------Employees-------
    #/employees
    url(r'^employees/$', views.EmployeesIndexView.as_view(), name='employee-index'),

    #/employees/search
    url(r'^employees/search/$', views.search_employees, name='employee-search'),

    #/employees/<employee_id>/
    url(r'^employee/(?P<pk>[0-9]+)/$', views.EmployeeDetailView.as_view(), name='employee-detail'),

    #/employee/add
    url(r'^employee/add/$', views.EmployeeCreate.as_view(), name='employee-add'),

    #/employee/<employee_id>/update/
    url(r'^employee/(?P<pk>[0-9]+)/update/$', views.EmployeeUpdate.as_view(), name='employee-update'),

    #/employee/<employee_id>/delete/
    url(r'^employee/(?P<pk>[0-9]+)/delete/$', views.EmployeeDelete.as_view(), name='employee-delete'),

    #employee/<employee_id>/flights
    url(r'^employee/flights/$', views.employee_flights, name='employee-flights'),

    #-------Users-------
    #/register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    #/login/
    url(r'^login/$', views.login_user, name='login'),

    #/logout/
    url(r'^logout/$', views.logout_user, name='logout'),

    # -------Bookings-------
    #/bookings/
    url(r'^bookings/$', views.BookingsView.as_view(), name='bookings'),

    #/bookings/confirmation/
    url(r'^bookings/confirmation/$', views.booking_confirmation, name='bookings-confirmation'),

    #/bookings/confirmed/
    url(r'^bookings/confirmed/$', views.booking_submitted, name='bookings-confirmed'),

    #/bookings/mybooking/
    url(r'^bookings/mybooking/$', views.get_booking, name='booking-detail'),

    #-------Other-------
    #Other
    url(r'^other/$', views.other_index, name='other-index'),

    #/plane/add
    url(r'^plane/add/$', views.PlaneCreate.as_view(), name='plane-add'),

    #/airport/add
    url(r'^airport/add/$', views.AirportCreate.as_view(), name='airport-add'),

    # /Departure/add
    url(r'^departure/add/$', views.DepartureCreate.as_view(), name='departure-add'),

    # /Arrival/add
    url(r'^arrival/add/$', views.ArrivalCreate.as_view(), name='arrival-add'),

]

flight/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse


class Person(models.Model):
    firstname = models.CharField(max_length=100)
    lastname = models.CharField(max_length=100)
    dob = models.DateField()
    address = models.CharField(max_length=500)

    class Meta:
        unique_together = ('firstname', 'lastname', 'dob')

    def __str__(self):
        return self.firstname + ' ' + self.lastname


class Employee(Person):
    salary = models.PositiveIntegerField()
    job = models.CharField(max_length=100)
    picture = models.FileField(default='anonymous.png')

    def name(self):
        return self.firstname + ' ' + self.lastname

    def get_absolute_url(self):
        return reverse('flight:employee-detail', kwargs={'pk': self.pk})


class AirCrew(Employee):
    total_flying_hours = models.PositiveIntegerField()


class Pilot(AirCrew):
    license_number = models.CharField(max_length=100, unique=True)


class Plane(models.Model):
    registration_number = models.CharField(max_length=20, unique=True)
    manufacturer = models.CharField(max_length=50)
    aircraft_model = models.CharField(max_length=50)
    nb_rows_of_seats = models.PositiveSmallIntegerField()
    nb_col_of_seats = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.manufacturer + ' ' + self.aircraft_model + ' - ' + self.registration_number

    def get_absolute_url(self):
        return reverse('flight:other-index')


class Airport(models.Model):
    three_letters_code = models.CharField(max_length=3)
    name = models.CharField(max_length=200, unique=True)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    def __str__(self):
        return self.name + ' (' + self.three_letters_code + ')'

    def get_absolute_url(self):
        return reverse('flight:other-index')


class Departure(models.Model):
    time = models.DateTimeField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)
    pilot_1 = models.ForeignKey(Pilot, related_name='pilot_1')
    pilot_2 = models.ForeignKey(Pilot, related_name='pilot_2')
    aircrew_1 = models.ForeignKey(AirCrew, related_name='aircrew_1')
    aircrew_2 = models.ForeignKey(AirCrew, related_name='aircrew_2')

    def __str__(self):
        return self.airport.name + ' - ' + str(self.time)

    def get_crew(self):
        return [self.pilot_1, self.pilot_2, self.aircrew_1, self.aircrew_2]

    def get_absolute_url(self):
        return reverse('flight:other-index')

    def save(self, *args, **kwargs):
        if self.pilot_1 == self.pilot_2 or self.aircrew_1 == self.aircrew_2:
            return reverse('flight:index')
        else:
            return super(Departure, self).save(*args, **kwargs)


class Arrival(models.Model):
    time = models.DateTimeField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)

    def __str__(self):
        return self.airport.name + ' - ' + str(self.time)

    def get_absolute_url(self):
        return reverse('flight:other-index')


class Flight(models.Model):
    flight_number = models.CharField(max_length=10, unique=True)
    plane = models.ForeignKey(Plane, on_delete=models.CASCADE)
    departure = models.OneToOneField(Departure, on_delete=models.CASCADE)
    arrival = models.OneToOneField(Arrival, on_delete=models.CASCADE)

    def total_seats_nb(self):
        return self.plane.nb_col_of_seats * self.plane.nb_rows_of_seats - self.booking_set.count()

    def get_absolute_url(self):
        return reverse('flight:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.flight_number


class Booking(models.Model):
    booking_number = models.CharField(max_length=50, unique=True)
    price = models.FloatField(default=100)
    flight = models.ForeignKey(Flight)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.booking_number


class Customer(Person):
    booking = models.ForeignKey(Booking)

flight/forms.py
from django.contrib.auth.models import User
from .models import Departure
from django.contrib.admin import widgets
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class IndexForm(forms.ModelForm):
    class Meta:
        model = Departure
        fields = ['time']

    def __init__(self, *args, **kwargs):
        super(IndexForm, self).__init__(*args, **kwargs)
        self.fields['time'].widget = widgets.AdminSplitDateTime()

flight/views.py
from django.views.generic import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.crypto import get_random_string
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import View
from .models import Flight, Employee, Booking, Airport, Plane, Departure, Arrival, Customer, AirCrew
from .forms import UserForm


#---------Flights---------
class IndexView(generic.ListView):
    template_name = 'flight/index.html'
    context_object_name = 'all_flights'

    def get_queryset(self):
        return Flight.objects.all().order_by('departure__time')


def search_flights(request):
    from datetime import datetime
    import pytz

    utc = pytz.UTC

    if request.method == 'POST':
        try:
            departuretime = datetime.strptime(request.POST['departuretime'], '%Y-%m-%d').replace(tzinfo=utc)
        except:
            departuretime = datetime.now().replace(tzinfo=utc)
        flight_nb = request.POST['flight_nb']

        all_flights = Flight.objects.filter(flight_number__startswith=flight_nb).order_by('departure__time')
        filtered_flights = []

        for flight in all_flights:
            if flight.departure.time >= departuretime:
                filtered_flights.append(flight)

        context = {
            'all_flights': filtered_flights,
        }

        return render(request, 'flight/index.html', context)


class DetailView(generic.DetailView):
    model = Flight
    template_name = 'flight/detail.html'


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class FlightCreate(CreateView):
    model = Flight
    fields = ['flight_number', 'plane', 'departure', 'arrival']


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class FlightUpdate(UpdateView):
    model = Flight
    fields = ['flight_number', 'plane', 'departure', 'arrival']


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class FlightDelete(DeleteView):
    model = Flight
    success_url = reverse_lazy('flight:index')


#---------Employees---------
@method_decorator(login_required(login_url='/login'), name='dispatch')
class EmployeesIndexView(generic.ListView):
    template_name = 'flight/employees.html'
    context_object_name = 'all_employees'

    def get_queryset(self):
        return Employee.objects.all().order_by('lastname')

@login_required
def search_employees(request):

    if request.method == 'POST':
        employee_firstname = request.POST['employee_firstname']
        employee_lastname = request.POST['employee_lastname']

        all_employees = Employee.objects.filter(firstname__contains=employee_firstname).filter(lastname__contains=employee_lastname).order_by('lastname')

        context = {
            'all_employees': all_employees,
        }

        return render(request, 'flight/employees.html', context)

@login_required
def employee_flights(request):
    if request.method == 'POST':
        employee_id = int(request.POST['employee_id'])
        employee = Employee.objects.get(id=employee_id)

        if employee.aircrew is not None:
            aircrew = employee.aircrew
            if aircrew.pilot is not None:
                aircrew = aircrew.pilot

        flights = []

        for departure in Departure.objects.all():
            crew = departure.get_crew()
            print(crew)
            if aircrew in crew:
                flights.append(departure.flight)

        context = {'all_flights': flights}

        return render(request, 'flight/employee-flights.html', context)

@method_decorator(login_required(login_url='/login'), name='dispatch')
class EmployeeDetailView(generic.DetailView):
    model = Employee
    template_name = 'flight/employee_detail.html'


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class EmployeeCreate(CreateView):
    model = Employee
    fields = ['firstname', 'lastname', 'dob', 'address', 'job', 'salary', 'picture']


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class EmployeeUpdate(UpdateView):
    model = Employee
    fields = ['firstname', 'lastname', 'dob', 'address', 'job', 'salary', 'picture']


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('flight:employee-index')


#---------Users---------
@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class UserFormView(View):
    form_class = UserForm
    template_name = 'flight/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            #Normalized data (formated properly)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #Check if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('flight:index')

        return render(request, self.template_name, {'form': form})


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_flights = Flight.objects.all()
                return render(request, 'flight/index.html', {'all_flights': all_flights})
            else:
                return render(request, 'flight/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'flight/login.html', {'error_message': 'Invalid login'})
    return render(request, 'flight/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'flight/login.html', context)


#---------Bookings---------
@method_decorator(login_required(login_url='/login'), name='dispatch')
class BookingsView(generic.ListView):
    template_name = 'flight/bookings.html'
    context_object_name = 'all_bookings'

    def get_queryset(self):
        return Booking.objects.all()


def get_booking(request):
    if request.method == 'POST':
        booking_nb = request.POST['booking_nb']

        booking = Booking.objects.filter(booking_number=booking_nb).first()

        context = {'booking': booking}

    return render(request, 'flight/booking-detail.html', context)


def booking_confirmation(request):
    if request.method == 'POST':
        nb_of_passengers = int(request.POST['nb_of_passengers'])
        flight_id = request.POST['flight']
        context = {
            'nb_of_passengers': nb_of_passengers,
            'range_nb_of_passengers': range(1, nb_of_passengers + 1),
            'flight': Flight.objects.get(id=int(flight_id)),
        }

        return render(request, 'flight/booking-confirmation.html', context)


def booking_submitted(request):
    if request.method == 'POST':
        nb_of_passengers = int(request.POST['nb_of_passengers'])
        flight = Flight.objects.get(id = int(request.POST['flight_id']))

        if flight.total_seats_nb() < nb_of_passengers:
            context = {
                'error_message': 'Not enough seats, your booking can not be completed !',
            }
            return render(request, 'flight/index.html', context)

        confirmed_bookings_list = []

        for i in range(1, nb_of_passengers + 1):
            try:
                b = Booking(booking_number=get_random_string(length=8).upper(), flight=flight)
                b.save()
                lastname = request.POST['lastname_passenger_' + str(i)]
                firstname = request.POST['firstname_passenger_' + str(i)]
                dob = request.POST['birthday_passenger_' + str(i)]
                address = request.POST['address_passenger_' + str(i)]
                c = Customer(firstname=firstname, lastname=lastname, dob=dob, address=address, booking=b)
                c.save()
                confirmed_bookings_list.append(b)
            except:
                continue

        context = {
            'flight': flight,
            'confirmed_bookings_list': confirmed_bookings_list,
        }

        return render(request, 'flight/booking-confirmed.html', context)


#----Other--------
@login_required
def other_index(request):
    all_airports_list = Airport.objects.all()
    all_planes_list = Plane.objects.all()
    all_departures_list = Departure.objects.all().order_by('time')
    all_arrivals_list = Arrival.objects.all().order_by('time')
    context = {
        'all_airports': all_airports_list,
        'all_planes': all_planes_list,
        'all_departures': all_departures_list,
        'all_arrivals': all_arrivals_list,
    }
    return render(request, 'flight/other.html', context)

#---------Plane---------

@method_decorator(login_required(login_url='/login'), name='dispatch')
class PlaneDetailView(generic.DetailView):
    model = Plane
    template_name = 'flight/plane_detail.html'


@method_decorator(staff_member_required(login_url='/login'), name='dispatch')
class PlaneCreate(CreateView):
    model = Plane

flight/templates/flight/airport_form.html
 {% extends 'flight/base.html' %}
 {% block title %}Add a New Airport{% endblock %}

 {% block body %}

    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="#" method="post">
                            {% csrf_token %}

                            {% include 'flight/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>

    </div>

 {% endblock %}

flight/templates/flight/departure_form.html
 {% extends 'flight/base.html' %}
 {% block title %}Add a New Departure{% endblock %}

 {% block body %}

    <div class="container-fluid">

        <div class="row">

            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">

                        <form class="form-horizontal" action="#" method="post">
                            {% csrf_token %}

                            {% include 'flight/form-template.html' %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

        </div>

    </div>
    <script>
        $('#id_time').datetimepicker({
            format: 'Y-m-d H:i'
        });
    </script>


 {% endblock %}

flight/templates/flight/employees.html
{% extends 'flight/base.html' %}
{% block title %}Employees{% endblock %}
{% block employee_index_active %}active{% endblock %}

{% block body %}

    <div class="container-fluid flights-container">

        <!-- Left Flight Search -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" role="search" method="post" action="{% url 'flight:employee-search' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2">Firstname</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="employee_firstname" value="" placeholder="ex: John"/>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2">Lastname</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="employee_lastname" value="" placeholder="ex: Doe"/>
                            </div>
                        </div>
                        <div class="col-sm-offset-8 col-sm-4">
                            <button type="submit" class="btn btn-default">Search</button>
                        </div>
                    </form>

                </div>
            </div>
            {% if user.is_staff %}
                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="col-sm-12 active">
                        <a href="{% url 'flight:employee-add' %}"><span class="glyphicon glyphicon-plus"></span> New Employee</a>
                    </li>
                </ul>
            {% endif %}
        </div>

        <!-- Right Employees List -->
        <div class="col-sm-8 col-md-9">

            {% if all_employees %}
            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Employees List</h3>

                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Address</th>
                                <th>Birthday</th>
                                <th>Job</th>
                                {% if user.is_staff %}
                                    <th>Current Monthly Salary</th>
                                    <th>Actions</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                        {% for employee in all_employees %}
                            <tr>
                                <td><a href="{% url 'flight:employee-detail' employee.id %}">{{employee}}</a></td>
                                <td>{{employee.address}}</td>
                                <td>{{employee.dob}}</td>
                                <td>{{employee.job}}</td>
                                {% if user.is_staff %}
                                <td>{{employee.salary}}€</td>
                                    <td>
                                        <a class="btn btn-primary btn-sml" href="{% url 'flight:employee-update' employee.id %}">
                                            <span class="glyphicon glyphicon-cog"></span>
                                        </a>
                                        <form action="{% url 'flight:employee-delete' employee.id %}" method="post" style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="album_id" value="{{employee.id}}"/>
                                            <button type="submit" class="btn btn-danger btn-sm">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                        </form>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
            {% endif %}

        </div>

    </div>
{% endblock %}

flight/templates/flight/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

flight/templates/flight/other.html
{% extends 'flight/base.html' %}
{% block title %}General Management{% endblock %}
{% block other_active %}active{% endblock %}

{% block body %}

    <!-- Left Plane List -->
    <div class="col-sm-6 col-md-6">
        {% if all_planes %}

        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Planes List</h3>

                {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif %}

                <table class="table">
                    <thead>
                        <tr>
                            <th>Registration Number</th>
                            <th>Manufacturer</th>
                            <th>Model</th>
                            <th>Nb of seats per row</th>
                            <th>Nb of rows</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for plane in all_planes %}
                        <tr>
                            <td>{{plane.registration_number}}</td>
                            <td>{{plane.manufacturer}}</td>
                            <td>{{plane.aircraft_model}}</td>
                            <td>{{plane.nb_rows_of_seats}}</td>
                            <td>{{plane.nb_col_of_seats}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
        {% endif %}
        {% if user.is_staff %}
        <ul class="nav nav-pills" style="margin-bottom: 10px;">
            <li role="presentation" class="col-sm-offset-6 col-sm-6 active">
                <a href="{% url 'flight:plane-add' %}"><span class="glyphicon glyphicon-plus"></span> New Plane</a>
            </li>
        </ul>
        {% endif %}
    </div>

    <!-- Right Airport List -->
    <div class="col-sm-6 col-md-6">
        {% if all_airports %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Airports List</h3>

                {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Name</th>
                            <th>City</th>
                            <th>Country</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for airport in all_airports %}
                        <tr>
                            <td>{{airport.three_letters_code}}</td>
                            <td>{{airport.name}}</td>
                            <td>{{airport.city}}</td>
                            <td>{{airport.country}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
        {% if user.is_staff %}
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="col-sm-offset-6 col-sm-6 active">
                    <a href="{% url 'flight:airport-add' %}"><span class="glyphicon glyphicon-plus"></span> New Airport</a>
                </li>
            </ul>
        {% endif %}
    </div>

    <!-- Left Departures List -->
    <div class="col-sm-6 col-md-6">
    {% if all_departures %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Departures List</h3>

                {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Time</th>
                            <th>Airport</th>
                            <th>Pilot 1</th>
                            <th>Pilot 2</th>
                            <th>Staff 1</th>
                            <th>Staff 2</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for departure in all_departures %}
                        <tr>
                            <td>{{departure.time}}</td>
                            <td>{{departure.airport}}</td>
                            <td>{{departure.pilot_1}}</td>
                            <td>{{departure.pilot_2}}</td>
                            <td>{{departure.aircrew_1}}</td>
                            <td>{{departure.aircrew_2}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
        {% endif %}
        {% if user.is_staff %}
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="col-sm-offset-6 col-sm-6 active">
                    <a href="{% url 'flight:departure-add' %}"><span class="glyphicon glyphicon-plus"></span> New Departure</a>
                </li>
            </ul>
        {% endif %}
    </div>

    <!-- Right Arrivals List -->
    <div class="col-sm-6 col-md-6">
        {% if all_arrivals %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h3>Arrivals List</h3>

                {% if error_message %}
                    <p><strong>{{error_message}}</strong></p>
                {% endif %}
                <table class="table">
                    <thead>
                        <tr>
                            <th>Time</th>
                            <th>Airport</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for arrival in all_arrivals %}
                        <tr>
                            <td>{{arrival.time}}</td>
                            <td>{{arrival.airport}}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}
        {% if user.is_staff %}
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="col-sm-offset-6 col-sm-6 active">
                    <a href="{% url 'flight:arrival-add' %}"><span class="glyphicon glyphicon-plus"></span> New Arrival</a>
                </li>
            </ul>
        {% endif %}
    </div>

{% endblock %}